#!/bin/bash
#
# put into /etc/bash_completion.d/
#
_pwsafe() 
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    opts='add query'

    if [ "$COMP_CWORD" -gt 1 ]; then
        return 0
    else
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    fi
}
complete -F _pwsafe pwsafe
