#!/bin/bash
#
# put into /etc/bash_completion.d/
#
_pwsafe() 
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    opts='--help -a --add -q --query --list --lock --unlock --dbfile'

    case "${prev}" in

        # requires file argument
	--dbfile)
            _filedir
            return 0
            ;;

        # requires some argument
        -q|--query|-a|--add)
            return 0
            ;;

        *)
            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
            ;;
    esac
}
complete -F _pwsafe pwsafe
